# LAB 10

### 10) Develop python program to read NumPy array and print row (sum,mean,std) and column (sum,mean,std).

In [6]:
from numpy import asarray
data= [[1,2,3],[4,5,6]]
data=asarray(data)
print('numpy array')
print(data)
print("_________________________")

totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("row sum")
print(totalr)
print("column sum")
print(totalc)
print("_________________________")

meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("row mean")
print(meanr)
print("Column mean")
print(meanc)
print("___________________________")
       
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("row std")
print(stdr)
print("Column std")
print(stdc)
       

numpy array
[[1 2 3]
 [4 5 6]]
_________________________
row sum
[ 6 15]
column sum
[5 7 9]
_________________________
row mean
[2. 5.]
Column mean
[2.5 3.5 4.5]
___________________________
row std
[0.81649658 0.81649658]
Column std
[1.5 1.5 1.5]
